# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        packages: [usafacts]
#        packages: [_delphi_utils_python, cdc_covidnet, claims_hosp, combo_cases_and_deaths, jhu, nchs_mortality, quidel, quidel_covidtest, safegraph, safegraph_patterns, usafacts]
    defaults:
      run:
        working-directory: ${{ matrix.packages }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install testing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools==49.2.1
        pip install pandas==1.1.1
        pip install pylint pytest
    - name: Install utils
      if: ${{ matrix.packages }} != '_delphi_utils_python'
      run: |
        python -m pip install --upgrade pip
        pip install pandas==1.1.0
        pip install ../_delphi_utils_python/
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip list
    - name: Lint with pylint
      run: |
        pylint *delphi_*
    - name: Test with pytest
      run: |
        (cd tests && pytest)
